options:
  merge-default-rules: false
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore:
rules:
  #
  # Default rules from grunt-sass-lint/.sass-lint.yml at master.
  #
  empty-line-between-blocks: 0
  extends-before-mixins: 1
  extends-before-declarations: 1
  indentation: 0
  name-format: 0
  nesting-depth: 0
  one-declaration-per-line: 1
  placeholder-in-extend: 1
  property-spelling: 0
  shorthand: 0
  space-after-colon: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1

  #
  # Add rules to turn off warnings.
  #
  border-zero: 0
  class-name-format: 0
  empty-args: 0
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  mixins-before-declarations: 0
  no-css-comments: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 0
  no-ids: 0
  no-important: 0
  no-qualifying-elements: 0
  no-vendor-prefixes: 0
  property-sort-order: 0
  pseudo-element: 0
  quotes: 0
  single-line-per-selector: 0
  space-after-comma: 0
  space-before-brace: 0
  variable-name-format:
    - 0
    - convention: hyphenatedbem
